# Generated by Django 2.0.1 on 2018-01-18 06:22

from django.conf import settings
from django.db import migrations, models
import hr.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(storage=hr.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('user', models.ForeignKey(on_delete=True, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
