# Generated by Django 2.0.1 on 2018-01-22 23:35

from django.db import migrations, models
import hr.storage_backends
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatedocument',
            name='user',
        ),
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(storage=hr.storage_backends.PrivateMediaStorage(), upload_to=upload.models.upload_to_path),
        ),
        migrations.DeleteModel(
            name='PrivateDocument',
        ),
    ]
