# Generated by Django 2.0.1 on 2018-01-23 02:57

from django.db import migrations, models
import hr.storage_backends
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20180123_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatedocument',
            name='upload',
            field=models.FileField(storage=hr.storage_backends.PrivateMediaStorage(), upload_to=upload.models.upload_to_path),
        ),
    ]
